title: " Helio Journal"
email: ""
description: "Journal by Helio - dev notes, insights, reflections."
baseurl: "/helio-journal"
url: "https://heliohashinaga.github.io"
theme: minima
markdown: kramdown
